// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetCPUPercentage() {
  return window['go']['main']['App']['GetCPUPercentage']();
}

export function GetDiskPercentage() {
  return window['go']['main']['App']['GetDiskPercentage']();
}
