// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetCPUPercentage():Promise<string>;

export function GetDiskPercentage():Promise<string>;

export function GetPorts(arg1:string,arg2:number):Promise<number>;

export function GetRAMPercentage():Promise<string>;
